GET http://localhost:8080/api/backgrounds/visionboard/1

###

GET http://localhost:8080/api/backgrounds/27

###

POST http://localhost:8080/api/backgrounds/1/add
Content-Type: application/json

{
    "backgroundLink": "./imedrtfhsdhsdhsdgfh1.jpg"
  }

###

DELETE http://localhost:8080/api/backgrounds/143/delete