GET http://localhost:8080/api/images/visionboard/1

###

GET http://localhost:8080/api/images/20


###

PATCH http://localhost:8080/api/images/updateimage
Content-Type: application/json

{
  "id": "2",
  "imageIsZoomed": true,
  "imageHasBorder": true,
  "imageBorderRadius": "2%",
  "imageRotate": 4,
  "imageIsFlipped": true,
  "imageParentElement": "block4"

}

###

DELETE http://localhost:8080/api/images/21/delete

###

POST http://localhost:8080/api/visionboards/1/addimage
Content-Type: application/json

{
  "imageHtmlId": "CrazyRussian",
  "imageIsZoomed": false,
  "imageLink": "/images/gallery-images/airplane.jpg",
  "imageHasBorder": false,
  "imageBorderRadius": "0px",
  "imageRotate": 0,
  "imageIsFlipped": false,
  "imageParentElement": "images-container"

}

###

PATCH http://localhost:8080/api/images/2/updateImageIsZoomed
Content-Type: application/json

{
"imageIsZoomed": "true"
}

###

PATCH http://localhost:8080/api/images/2/updateImageHasBorder
Content-Type: application/json

{
  "imageHasBorder": "true"
}

###

PATCH http://localhost:8080/api/images/2/updateImageBorderRadius
Content-Type: application/json

{
  "imageBorderRadius": "50"
}

###

PATCH http://localhost:8080/api/images/2/updateImageRotate
Content-Type: application/json

{
  "imageRotate": "180"
}

###

PATCH http://localhost:8080/api/images/2/updateImageIsFlipped
Content-Type: application/json

{
  "imageIsFlipped": "true"
}

###