GET http://localhost:8080/api/quotes/visionboard/1

###

GET http://localhost:8080/api/quotes/23

###


DELETE http://localhost:8080/api/quotes/23/delete

###

POST http://localhost:8080/api/visionboards/1/addquote
Content-Type: application/json

{
  "quoteHtmlId": "updated-img2000",
  "quoteIsZoomed": true,
  "quoteLink": "/images/quotes/quote1.png",
  "quoteHasBorder": true,
  "quoteBorderRadius": "0000px",
  "quoteRotate": 3,
  "quoteIsFlipped": true,
  "quoteParentElement": "quotes-asdasdfasdfasdf"
}

###

PATCH http://localhost:8080/api/quotes/4/updateQuoteIsZoomed
Content-Type: application/json

{
  "quoteIsZoomed": "true"
}

###

PATCH http://localhost:8080/api/quotes/4/updateQuoteHasBorder
Content-Type: application/json

{
  "quoteHasBorder": "true"
}

###

PATCH http://localhost:8080/api/quotes/4/updateQuoteBorderRadius
Content-Type: application/json

{
  "quoteBorderRadius": "50%"
}

###