GET http://localhost:8080/api/texts/visionboard/1

###

GET http://localhost:8080/api/texts/7

###

GET http://localhost:8080/api/1/texts/text10

###

DELETE http://localhost:8080/api/texts/7/delete

###

POST http://localhost:8080/api/visionboards/1/addtext
Content-Type: application/json

{
  "textHtmlId": "text5",
  "textContent": "Dream Big with Nick!",
  "fontSize": "12pt",
  "hasFontShadow": false,
  "fontShadowColor": "#393E41",
  "fontColor": "#393E41",
  "fontFamily": "Amaranth",
  "textParentElement": "block9",
  "fontBold": true,
  "fontItalicized": true,
  "fontUnderlined": false

}

###

PATCH http://localhost:8080/api/texts/7/updateTextContent
Content-Type: application/json

{
 "textContent": "Update"
}

###

PATCH http://localhost:8080/api/texts/7/updateFontSize
Content-Type: application/json

{
  "fontSize": "15pt"
}

###

PATCH http://localhost:8080/api/texts/7/updateHasFontShadow
Content-Type: application/json

{
  "hasFontShadow": "true"
}

###

PATCH http://localhost:8080/api/texts/7/updateFontShadowColor
Content-Type: application/json

{
  "fontShadowColor": "#393E43"
}

###

PATCH http://localhost:8080/api/texts/7/updateFontColor
Content-Type: application/json

{
  "fontColor": "#393E42"
}

###

PATCH http://localhost:8080/api/texts/7/updateFontFamily
Content-Type: application/json

{
  "fontFamily": "Ariel"
}

###

PATCH http://localhost:8080/api/texts/7/updateIsFontBold
Content-Type: application/json

{
  "fontBold": true
}

###

PATCH http://localhost:8080/api/texts/7/updateIsFontItalicized
Content-Type: application/json

{
  "fontItalicized": true
}

###

PATCH http://localhost:8080/api/texts/7/updateIsFontUnderlined
Content-Type: application/json

{
  "fontUnderlined": true
}

###

PATCH http://localhost:8080/api/texts/7/updateTextParentElement
Content-Type: application/json

{
  "textParentElement": "text-container"
}

###