GET http://localhost:8080/api/visionboards

###

GET http://localhost:8080/api/visionboards/28


###

POST http://localhost:8080/api/visionboards/add/johnsdadd


###
PATCH http://localhost:8080/api/visionboards/1/updateThemeDark
Content-Type: application/json

{
  "themeDark": "false"
}

###
PATCH http://localhost:8080/api/visionboards/1/updateBackgroundColor
Content-Type: application/json

{
  "backgroundColor": "#fgfgfg"
}

###
PATCH http://localhost:8080/api/visionboards/1/updateGridSpacing
Content-Type: application/json

{
  "gridSpacing": "28px"
}