GET http://localhost:8080/api/visionboards

###

GET http://localhost:8080/api/visionboards/10


###

PATCH http://localhost:8080/api/visionboards/10/update
Content-Type: application/json

{
  "id": 10,
  "hasGrid": false,
  "gridSpacing": "100px",
  "gridBorderRadius": "100%",
  "gridBorderThickness": "50px",
  "gridBorderColor": "#0000",
  "gridBorderStyle": "dotted",
  "backgroundImageLink": "asdf",
  "backgroundColor": "#0000",
  "gridTemplateName": "5"
}

###

DELETE http://localhost:8080/api/visionboards/2/delete

###

POST http://localhost:8080/api/images/addimage
Content-Type: application/json

{
  "imageName": "CrazyRussian",
  "imageIsZoomed": false,
  "imageLink": "/images/gallery-images/airplane.jpg",
  "imageHasBorder": false,
  "imageBorderRadius": "0px",
  "imageRotate": 0,
  "imageIsFlipped": false,
  "imageParentElement": "images-container"

}
